#!/usr/bin/env bash
#Lucky numbers with if, elif, and else on a while loop
x=1
while [ $x -le 10 ]
do
if [ $x -eq 4 ]
then echo "bad luck"
elif [ $x -eq 8 ]
then echo "good luck"
else echo "Best School"
fi
((x++))
done
